package com.liferay62.servicio.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay62.servicio.model.Registro;
import com.liferay62.servicio.service.RegistroLocalServiceUtil;

/**
 * The extended model base implementation for the Registro service. Represents a row in the &quot;RegistroSolicitud_Registro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistroImpl
 * @see com.liferay62.servicio.model.Registro
 * @generated
 */
public abstract class RegistroBaseImpl extends RegistroModelImpl
    implements Registro {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a registro model instance should use the {@link Registro} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RegistroLocalServiceUtil.addRegistro(this);
        } else {
            RegistroLocalServiceUtil.updateRegistro(this);
        }
    }
}
